apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-12-15T05:54:48Z
    generation: 1
    labels:
      run: hello-node
    name: hello-node
    namespace: default
    resourceVersion: "1132"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hello-node
    uid: 75cb0038-e15c-11e7-947d-525400ee3d5e
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: hello-node
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: hello-node
      spec:
        containers:
        - image: hello-node:v1
          imagePullPolicy: IfNotPresent
          name: hello-node
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: 2017-12-15T05:54:48Z
      lastUpdateTime: 2017-12-15T05:54:48Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
